---
# only accessible via jellyfin.imaginator.com
# https://github.com/toomuchio/jellyfin-nginx-reverseproxy

- name: Install packages
  ansible.builtin.package:
    name:
      - podman
    state: present

- name: create jellyfin group
  ansible.builtin.group:
    name: jellyfin
    state: present

- name: ensure media group exists
  ansible.builtin.group:
    name: media
    state: present

- name: create jellyfin user
  ansible.builtin.user:
    name: jellyfin
    group: jellyfin
    system: true
    home: /var/lib/jellyfin
    groups: media
    createhome: true
    shell: /bin/false
    state: present

- name: creates jellyfin directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: jellyfin
    group: jellyfin
    mode: 0775
  with_items:
    - /var/lib/jellyfin/config
    - /var/tmp/jellyfin/cache

# needs /etc/sub[ug]id of
# simon:100000:65536
# jellyfin:165536:65536

- name: Create jellyfin-podman systemd service file
  ansible.builtin.template:
    src: jellyfin-podman.service
    dest: /lib/systemd/system/jellyfin-podman.service
    owner: root
    group: root
    mode: 0664
  notify: restart jellyfin-podman

- name: Create jellyfin-podman nginx vhost
  ansible.builtin.template:
    src: jellyfin.imaginator.com.conf
    dest: /etc/nginx/sites-enabled/jellyfin.imaginator.com.conf
    owner: www-data
    group: www-data
    mode: 0660
  notify: reload nginx
