- hosts: bunker
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    lxc_bridge_interface: trusted
  tasks:
    - { import_role: { name: lxc-containers }, tags: [ 'lxc-containers' ] }                      # build our containers
