- name: lxc packages are installed on host
  apt:
    pkg:
    - lxc
    - lxctl
    - lxc-dev
    - lxc-templates
  
- copy:
    dest: /etc/default/lxc-net
    content: |
      USE_LXC_BRIDGE="false"

- copy:
    dest: /etc/lxc/default.conf
    content: |
      lxc.net.0.type = macvlan
      lxc.net.0.macvlan.mode = bridge
      lxc.net.0.link = {{ lxc_bridge_interface }}
      lxc.net.0.flags = up
      lxc.net.0.hwaddr = 00:16:3e:xx:xx:xx

- service:
    name: lxc-net
    state: started

- name: Load in local SSH key path
  set_fact:
    my_ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_simon.pub"

- name: interface device exists
  command: ip addr show trusted
  changed_when: false
  run_once: true

- name: containers exist and have local SSH key
  lxc_container:
    name: "{{ item }}"
    container_log: true
    container_log_level: debug
    template: ubuntu
    state: started
    template_options: --release jammy
    container_config:
      - "lxc.net.0.ipv4.address = {{ hostvars[item].ansible_host }}/24"
      - "lxc.net.0.ipv4.gateway = auto"
      - "lxc.net.0.link = {{ lxc_bridge_interface }}"
      - "lxc.net.0.macvlan.mode = bridge"
      - "lxc.net.0.type = macvlan"
      - "lxc.start.auto = 1"
      - "lxc.uts.name = {{ item }}"
#    container_command: |
#        if [ ! -d ~/.ssh ]; then
#          mkdir ~/.ssh
#          echo "{{ lookup('file', my_ssh_key) }}" | tee -a ~/.ssh/authorized_keys
#        fi
  loop: "{{ query('inventory_hostnames', 'lxc_containers') }}"
