---

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart plex-podman
  ansible.builtin.service:
    name: plex-podman
    enabled: true
    state: restarted
    daemon_reload: true
