---
- name: install transmission
  ansible.builtin.package:
    name:
      - transmission-daemon
    state: present

- name: adding transmission-daemon to group media
  ansible.builtin.user:
    name: debian-transmission
    groups: media
    append: true

- name: transmission configs
  ansible.builtin.template:
    dest: /etc/transmission-daemon/settings.json
    owner: root
    group: root
    mode: 0664
    src: settings.json
  notify:
    - transmission changes

- name: Create transmission nginx vhost
  ansible.builtin.template:
    src: transmission.imagilan.conf
    dest: /etc/nginx/sites-enabled/transmission.imagilan.conf
    owner: www-data
    group: www-data
    mode: 0660
  notify:
    - reload nginx

- name: Create transmission service
  ansible.builtin.template:
    src: transmission.service
    dest: /lib/systemd/system/transmission-daemon.service
    owner: www-data
    group: www-data
    mode: 0660
  notify:
    - transmission changes

- name: rmem_max
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '16777216'
    sysctl_set: true
    state: present
    reload: true

- name: wmem_max
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: '4194304'
    sysctl_set: true
    state: present
    reload: true
