# **** DEFAULT Variables ***
#
# - Variables without a default value are MANDATORY except there is a condition. 
#    - In this case it is only mandatory if the condition is true. e.g variable 'system_update_notification_email'
#
# - The default value is used if the variable is not defined in your configuration
#
# **************************
default_variables: {
    "location":       {},                                         # "52.3476672,13.6215805" => latitude / longitude
    "timezone":       {},                                         # "Europe/Berlin"
    "language":       {},                                         # "en", "de" ...
    "country":        {},                                         # "EN", "DE" ...
    "region":         {}                                         # "bb" => berlin / brandenburg => https://www.openhab.org/docs/configuration/actions.html#ephemeris
}
