---
- name: Install the latest version of firewalld
  ansible.builtin.package:
    name:
      - firewalld
    state: latest

# no ansible way to set the default zone so, 
- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=drop

# trusted
- ansible.posix.firewalld:
    zone: trusted
    interface: trusted
    permanent: yes
    state: enabled
    immediate: true

- firewalld:
    zone: trusted
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- firewalld:
    zone: trusted
    service: http
    permanent: true
    state: enabled
    immediate: true

# notrust + iot

- ansible.posix.firewalld:
    zone: drop
    interface:
      - notrust
    permanent: yes
    state: enabled
    immediate: true

- ansible.posix.firewalld:
    zone: drop
    interface:
      - iot
    permanent: yes
    state: enabled
    immediate: true

- firewalld:
    zone: public
    service: ssh
    permanent: true
    state: enabled
    immediate: true

- firewalld:
    zone: public
    service: syslog
    permanent: true
    state: enabled
    immediate: true

- firewalld:
    zone: public
    port: 51413/tcp 
    permanent: yes
    state: enabled
    immediate: true
