- name: Create a new database with name 'bobdata'
  community.mysql.mysql_db:
    name: photoprism
    state: present

- name: create database user
  community.mysql.mysql_user:
    name: photoprism-db-user
    password: 12345
    priv: 'photoprism.*:ALL'
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Run Photoprism
  containers.podman.podman_container:
    name: photoprism
    image: docker.io/photoprism/development
    state: started
    volumes:
        - /srv/photos/:/photoprism/originals
        - /tmp/photoprism/thumbs:/photoprism/.cache/photoprism
    env:
        PHOTOPRISM_ADMIN_PASSWORD="insecure"
        PHOTOPRISM_DATABASE_NAME="photoprism"
        PHOTOPRISM_DATABASE_PASSWORD="photoprism"
        PHOTOPRISM_DATABASE_SERVER=127.0.0.1:5432
        PHOTOPRISM_DATABASE_USER="photoprism"
        PHOTOPRISM_DEBUG=true
        PHOTOPRISM_DETECT_NSFW=false
        PHOTOPRISM_EXPERIMENTAL=false 
        PHOTOPRISM_HTTP_HOST=0.0.0.0
        PHOTOPRISM_HTTP_PORT=2342
        PHOTOPRISM_JPEG_QUALITY=92
        PHOTOPRISM_JPEG_SIZE=7680
        PHOTOPRISM_ORIGINALS_PATH=/photoprism/originals
        PHOTOPRISM_PUBLIC=false
        PHOTOPRISM_READONLY=true 
        PHOTOPRISM_SERVER_MODE=debug
        PHOTOPRISM_SETTINGS_HIDDEN=false
        PHOTOPRISM_SIDECAR_JSON=true
        PHOTOPRISM_SIDECAR_YAML=true
        PHOTOPRISM_SITE_AUTHOR="Simon"
        PHOTOPRISM_SITE_CAPTION="Browse your life"
        PHOTOPRISM_SITE_DESCRIPTION="Nothing"
        PHOTOPRISM_SITE_TITLE="My Photobook"
        PHOTOPRISM_SITE_URL=http://localhost:2342/
        PHOTOPRISM_THUMB_FILTER=lanczos
        PHOTOPRISM_THUMB_SIZE_UNCACHED=7680
        PHOTOPRISM_THUMB_SIZE=2048
        PHOTOPRISM_THUMB_UNCACHED=false
        PHOTOPRISM_UPLOAD_NSFW=true 
