---

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: restart jellyfin
  systemd:
    name: jellyfin
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
