---

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded

- name: restart jellyfin-podman
  ansible.builtin.service:
    name: jellyfin-podman
    enabled: true
    state: restarted
    daemon_reload: true
